### ISSUE TITLE
Error: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by namse** [skatpgusskat/twitch-channel-feed#2]
```
{ Error: spawn /bin/sh ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn /bin/sh',
path: '/bin/sh',
spawnargs: 
[ '-c',
'./ffmpeg -i /tmp/555b327f-490f-4591-92d2-79f895e4137d -c:v libx264 -vf "scale=w=min(iw\\,300):h=-2" -crf 24 /tmp/03921fa6-8998-4392-b654-e17d7ec664f7.mp4' ],
cmd: './ffmpeg -i /tmp/555b327f-490f-4591-92d2-79f895e4137d -c:v libx264 -vf "scale=w=min(iw\\,300):h=-2" -crf 24 /tmp/03921fa6-8998-4392-b654-e17d7ec664f7.mp4',
stdout: '',
stderr: '' }
```

**Comment by namse** [comment]
Fix this problem, compiling typescript by ourselves
